(function(g){var window=this;var V4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.C,displayName:g.mH(a),kind:a.A,name:a.B,id:a.Aa,is_servable:a.M,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},W4=function(a){return a.g?a.g.languageCode:a.l},Xva=function(a,b){var c=new g.lH;
c.l=a.l;c.C=a.C;c.B=a.B;c.A=a.A;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},Yva=function(a){a=g.jd(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Ed(a[b])},Zva=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},X4=function(a){if(!$va.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(awa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},Y4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.UO.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.B=f;this.l=k},Z4=function(a,b,c,d,e){g.UO.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},a5=function(a){a=void 0===a?{}:a;
var b="_"+$4++;return new Z4(0,0x8000000000000,0,b,a)},b5=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.kb);a.params.kb&&g.Ga(l,a.params.kb);g.Ga(l,c.kb);k.kb=l;g.X.call(this,{G:"div",L:"caption-window",T:{id:"caption-window-"+a.id,dir:1==k.ak?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{G:"span",L:"captions-text"}]});this.o=[];this.I=!1;this.D=a;this.C=[];this.F=[];this.wa=e;this.na=f;this.B=null;this.W=.96*e;this.da=.96*f;this.l=k;this.ma=c;this.A=this.sa["captions-text"];this.fa=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.K=d/360*16;this.type=0;this.Y=this.K*bwa(l);a=new g.ZE(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.ZK,this);a.subscribe("dragmove",this.YK,this);a.subscribe("dragend",this.XK,this);this.ca=this.ba=0;a="";this.l.lk&&(a=X4(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.lk+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":cwa[this.l.textAlign]};this.fa&&(b["border-radius"]=a?this.Y/
8+"px":"");g.ih(this.element,b);switch(this.l.Ug){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},bwa=function(a){var b=1+.25*(a.dj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},c5=function(a,b){var c={},d=b.background?b.background:a.l.kb.background;
if(null!=b.Ze||b.background){var e=null!=b.Ze?b.Ze:a.l.kb.Ze;d=X4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Y/8+"px")}if(null!=b.dj||null!=b.offset)c["font-size"]=a.K*bwa(b)+"px";d=1;e=b.color||a.l.kb.color;if(b.color||null!=b.Gh)e=X4(e),d=null==b.Gh?a.l.kb.Gh:b.Gh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Uh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.mw&&
(k=e=b.mw);var l=a.K/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.MD()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.kb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ks&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.wr&&(c.visibility="hidden");return c},dwa=function(a,b,c){a.I=a.I||!!c;
var d={};g.Ga(d,a.l.kb);g.Ga(d,c||b.l);g.Ga(d,a.ma.kb);c=a.C[0];if(c&&d.background==c.background&&d.Ze==c.Ze&&!!d.wr==!!c.wr&&d.Uh==c.Uh){var e;for(e=0;e<a.C.length;e++)if(Zva(d,a.C[e])){var f=a.F[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.yd("SPAN");g.ih(f,c5(a,e));a.F[0].appendChild(f);e=1}a.F.length=e;a.C.length=e}else a.F.length=0,a.C.length=0,f=g.yd("SPAN"),g.ih(f,c5(a,d)),a.A.appendChild(f);a.B&&a.B.parentNode!=f&&(g.Ed(a.B),f.appendChild(a.B));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.o.length||!b.B){if(0<e||0!=a.o.length){var m=g.yd("BR");f.appendChild(m)}f.appendChild(g.zd("\u00a0"));a.B=g.zd("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.zd(l):l,m))}a.C.push(d);a.F.push(f);a.o.push(b)},ewa=function(){},e5=function(){this.A=this.l=this.mode=this.o=0;
this.B=new d5(this);this.C=new d5(this);this.g=[];this.clear()},gwa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Mm:a,
Nm:b,result:0};a=fwa[a];b=fwa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{Mm:a,Nm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Mm:a,Nm:b,result:2};return{Mm:a,Nm:b,result:3}},iwa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,hwa(a.B,b,c,d))},jwa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?iwa(a,d.hw,d.iw,b):1==d.type&&a.o&496&&hwa(a.C,d.hw,d.iw,b)}a.g.length=0},f5=function(){this.g=0},g5=function(){this.l=this.o=this.g=0},h5=function(){this.timestamp=this.te=0;
this.g=!1},i5=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new h5}this.g=this.l=this.Ec=0;this.style=new f5;this.B=a;this.A=0},j5=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.te){0==c&&(c=m,d=q);n=String.fromCharCode(r.te);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.te||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.te,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},owa=function(a,b){switch(a){case 0:return kwa[(b&127)-32];
case 1:return lwa[b&15];case 2:return mwa[b&31];case 3:return nwa[b&31]}return 0},k5=function(a){return a.o[a.Ec][a.l]},l5=function(a,b,c){2<=b&&1<a.l&&(--a.l,k5(a).te=0);
var d=k5(a);d.timestamp=a.B.l+0;d.te=owa(b,c);32>a.l&&a.l++},pwa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].gn(a.o[c+e][f])},m5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},n5=function(a){a.Ec=0<a.g?a.g:1;
a.l=1;m5(a,0,15)},o5=function(a){this.A=a;
this.B=0;this.style=new f5;this.C=new i5(a);this.D=new i5(a);this.F=new i5(a);this.l=this.C;this.o=this.D;this.g=this.l},p5=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:j5(d,c),n5(a.l),n5(a.o),d.Ec=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(j5(d,c),m5(d,d.Ec-d.g,b)):d.Ec<b&&(b=d.g),d.g=b)},qwa=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},rwa=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},d5=function(a){this.l=a;
this.g=new g5;this.B=0;this.o=new o5(a);this.C=new o5(a);this.A=this.o},hwa=function(a,b,c,d){a.g.update();
b=gwa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Mm;c=b.Nm;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&l5(a,0,b),c&96&&l5(a,0,c),0!=b&&0!=c&&3==a.style.g&&j5(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.Ec;break;case 3:if(d!=c.Ec){if(d<c.g&&(d=c.g,d==c.Ec))break;var f=1+c.Ec-c.g,k=1+d-c.g;pwa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));m5(c,b,e)}}c.Ec=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:l5(b.g,0,32);break a;case 48:57==c?(b=b.g,k5(b).te=0,32>b.l&&b.l++):l5(b.g,1,c&15)}break;case 2:c&32&&l5(b.g,2,c&31);break;case 3:c&32&&l5(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:qwa(b);break;case 33:b=
b.g;1<b.l&&(--b.l,k5(b).te=0);break;case 36:b=b.g;d=k5(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:p5(b,2,d);break;case 38:p5(b,3,d);break;case 39:p5(b,4,d);break;case 40:l5(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);n5(d);rwa(b);break;case 43:rwa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:j5(a,d)}m5(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Ec){++a.Ec;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.Ec<a.g&&(a.Ec=a.g));b=a.Ec-a.g+1;j5(a,d);pwa(a,b,b+1,a.g-1);m5(a,a.Ec,1)}break;case 46:m5(b.o,0,15);break;case 47:j5(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;qwa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},q5=function(){},r5=function(a){this.o=a;
this.l=null},twa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Nr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");swa(d,e,k,b,f,a.firstChild,{},c)},swa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.ks=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");s5.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new Y4(a,b,c,d,n.nodeValue,e||0<m,g.Tb(k)?void 0:k));else{var q={};g.Ga(q,k);swa(a,b,c,d,e||0<m,n,q,l)}}},t5=function(){this.o={};
this.l=null},u5=function(a){this.l={};
this.B={};this.C={};this.o="_"+$4++;this.A=a},v5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},w5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},x5=function(a,b){var c=v5(a,b);
if(void 0!=c)return c},y5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return s5.test(c),c},uwa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.C[d]:a.A);d=x5(b,"mh");null!=d&&(c.Bs=d);d=x5(b,"ju");null!=d&&(c.textAlign=d);d=x5(b,"pd");null!=d&&(c.ak=d);d=y5(b,"wfc");null!=d&&(c.windowColor=d);d=v5(b,"wfo");void 0!=d&&(c.lk=d/255);return c},vwa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.B[d]);d=x5(b,"ap");null!=d&&(c.Ug=d);d=v5(b,"cc");null!=d&&(c.NG=d);d=v5(b,"ah");null!=d&&(c.pi=d);d=v5(b,"rc");null!=d&&(c.Uo=d);d=v5(b,"av");null!=d&&(c.Ni=d);return c},wwa=function(a,b,c){var d={};
g.Ga(d,vwa(a,b));g.Ga(d,uwa(a,b));c?Zva(d,a.A)?(c=a.o,d=a.A):c="_"+$4++:c=b.getAttribute("id")||"0";a=v5(b,"t");b=v5(b,"d")||0x8000000000000;return new Z4(a,b,0,c,d)},z5=function(a,b,c){this.D=c;
this.version=this.B=this.C=this.g=0;this.l=new window.DataView(a);this.o=[]},A5=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},xwa=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},B5=function(a,b){this.o=a;
this.track="CC3"==b.C?4:0;this.l=new e5;this.l.o=1<<this.track},zwa=function(a){if(g.u(a))return!1;
a=new z5(a,8,0);return ywa(a)},ywa=function(a){if(!(a.g<a.l.byteLength)||1380139777!=xwa(a))return!1;
a.version=A5(a);if(1<a.version)return!1;A5(a);A5(a);A5(a);return!0},Awa=function(){this.l=[];
this.g=[]},C5=function(a,b){return b?a.g.concat(a.l):a.g},D5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ka(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.Ka(c,(0,g.z)(b.I,b))||c.push(b)}},E5=function(){this.l=null},Bwa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.ks=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new Y4(b,c,d,e.id,q.nodeValue,f||0<n,g.Tb(l)?void 0:l),m.push(q),e!=a.l&&e.l.push(q);else{var r={};g.Ga(r,l);Bwa(a,b,c,d,e,!0,q,r,m)}}},F5=function(a){var b=0;
a=g.na(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},G5=function(a){g.M.call(this);
this.vy=!!a;this.l=new Awa;this.D=[];this.g=null},Dwa=function(a){var b={};
if(a=W4(a))b.lang=a,Cwa.test(a)&&(b.ak=1);return b},Ewa=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.u(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.HH(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),zwa(b)||(b=g.Zd(new window.Uint8Array(b))))}if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new E5),a.g.g(b,d);b=g.Nr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new u5(Dwa(c)):a.g=new t5:a.g=new r5(Dwa(c)));return a.g.g(b,d)}try{if(zwa(b))return a.g||(a.g=
new B5(e,c)),a.g.g(b,d)}catch(k){g.iD(k)}return[]},H5=function(a){G5.call(this,a.Tm);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},I5=function(){this.qb=[]},J5=function(a,b,c,d,e,f){g.M.call(this);
this.C=b;this.A=new I5;this.g=null;this.D=d;this.I=f;this.l=this.o=null;this.K=c;this.B=e||!1;this.F=new g.Nt(this.Ky,1E3,this);g.N(this,this.F);this.H=new g.UE(this);g.N(this,this.H);this.H.O(b,"seekto",this.wz);this.wz(b.getCurrentTime());this.Ky()},Fwa=function(a,b){var c=g.lJ(b,{}).Oa(),d={format:"RAW",
ad:(0,g.z)(a.MQ,a),withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.l=g.DD(c,d);a.o=b;c=a.A;d=a.o.xa[0].ra;var e=g.cb(c.qb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.qb[e-1]&&e<c.qb.length&&1==c.qb[e]-d?(g.Ra(c.qb,e),g.Ra(c.qb,e-1)):0<e&&1==d-c.qb[e-1]?c.qb[e-1]=d:e<c.qb.length&&1==c.qb[e]-d?c.qb[e]=d:(g.Ya(c.qb,e,0,d),g.Ya(c.qb,e+1,0,d)))},K5=function(a,b){G5.call(this);
this.A=a;this.B=b;this.o=null;this.C=!1},Gwa=function(a,b){if(b in a.A.g)return a.A.g[b];
if(g.KJ(a.A))for(var c in a.A.g){var d=a.A.g[c];if(g.wG(d.info.mimeType))return d}return null},Hwa=function(a,b){return a.ya||g.W(b).Wa&&null!=a.oa&&null!=a.oa.g.rawcc},L5=function(a,b,c,d,e,f){b5.call(this,a,b,c,d,e,f);
this.type=1},M5=function(a,b,c,d,e,f){b5.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.H=this.M=0;this.N=window.NaN;this.ka=null;this.X=new g.Nt(this.QQ,433,this);g.N(this,this.X)},N5=function(a){if(!a.M){var b=g.yd("SPAN");
g.ih(b,c5(a,a.l.kb));a.A.appendChild(b);b.appendChild(g.zd("M"));var c=b.offsetHeight,d=g.yd("BR");b.appendChild(d);b.appendChild(g.zd("M"));a.M=b.offsetHeight-c;a.A.removeChild(b)}return a.M},O5=function(a,b,c,d){G5.call(this,d);
c=c||g.uD(a).hl||"";c=c.split("_").join("-");this.B=g.wD(a,{hl:c});this.A=b;this.C={};this.o=null},P5=function(a,b,c,d){var e=g.U("YTP_VIDEO_SUBTITLES_OVERRIDE"),f=new g.fZ(b,void 0,e);
g.u_.call(this,Iwa(d),a,b,c,e,function(){return g.nZ(c,f)});
g.S(this.element,"ytp-subtitles-options-menu-item");this.I=d.option.toString();a=d.options;this.K=g.ib(a,this.hA,this);this.F=f;g.N(this,this.F);b=new g.cZ({G:"div",L:"ytp-menuitemtitle",J:[g.U("YTP_VIDEO_SUBTITLES_OVERRIDE_DESC")]},0);g.N(this,b);g.gZ(this.F,b,!0);this.B=new g.cZ({G:"div",L:"ytp-menuitem",T:{role:"menuitemradio",tabindex:"0"},J:[{G:"div",L:"ytp-menuitem-label",J:[g.U("YTP_ON")]}]},-1);g.N(this,this.B);g.gZ(this.F,this.B,!0);this.O(this.B.element,"click",g.Fa(this.iA,!0));this.l=
new g.cZ({G:"div",L:"ytp-menuitem",T:{role:"menuitemradio",tabindex:"0"},J:[{G:"div",L:"ytp-menuitem-label",J:[g.U("YTP_OFF")]}]},-2);g.N(this,this.l);g.gZ(this.F,this.l,!0);this.O(this.l.element,"click",g.Fa(this.iA,!1));g.v_(this,(0,g.I)(a,this.hA))},Iwa=function(a){return(a.message?g.U(a.message):a.text)||""},Q5=function(a,b){g.fZ.call(this,a,void 0,g.U("YTP_OPTIONS"));
this.l={};for(var c=0;c<g.GZ.length;c++){var d=g.GZ[c],e=new P5(-c,a,b,d);g.N(this,e);e.subscribe("settingChange",this.o,this);this.l[d.option.toString()]=e;g.gZ(this,e,!0)}c=new g.cZ(g.dZ(),-g.GZ.length,g.U("YTP_RESET"));g.N(this,c);c.R("click",(0,g.z)(this.o,this,"reset",!0));g.gZ(this,c,!0)},Jwa=function(a,b){for(var c in b){var d=a.l[c];
if(d){var e=b[c].toString(),f=!!b[c+"Override"];d.o[e]&&(d.qf(e),d.B.element.setAttribute("aria-checked",!f),d.l.element.setAttribute("aria-checked",f))}}},R5=function(a,b){g.u_.call(this,g.U("YTP_AUTO_TRANSLATE"),0,a,b);
this.l={}},S5=function(a,b){var c=new Q5(a,b);
g.u_.call(this,g.U("YTP_SUBTITLES"),3,a,b,g.U("YTP_OPTIONS"),function(){return g.nZ(b,c)});
this.l=a;this.B={};this.M=new g.Nt(g.Fa(this.gA,!1),3E3,this);g.N(this,this.M);this.I=new g.X({G:"div",J:[{G:"span",J:[g.U("YTP_SUBTITLES")]},{G:"span",L:"ytp-menuitem-label-count",J:["{{content}}"]}]});g.N(this,this.I);g.bZ(this,this.I);this.F=new R5(a,b);g.N(this,this.F);this.F.subscribe("select",this.eN,this);this.K=c;g.N(this,this.K);this.K.subscribe("settingChange",this.dN,this);this.O(a,"videodatachange",this.yl);this.O(a,"onApiChange",this.yl);this.O(a,"onCaptionsTrackListChanged",this.yl);
this.O(a,"captionschanged",this.yl);this.yl()},V5=function(a){g.hU.call(this,a);
g.gG({YTP_CLICK_FOR_SETTINGS:"Click $GEAR_ICON for settings",YTP_SAMPLE_SUBTITLES:"Captions look like this"});this.o=g.W(a);this.A=a.ea();this.ma=g.HT(a);this.I=a;var b=null,c=g.FC("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.tC(c));this.ba=b;this.C={kb:{}};this.H={kb:{}};this.M=[];this.V={};this.Y={};this.N=!1;this.na="1"==this.A.hc.cc_auto_caps||"1"==this.o.xd.cc_auto_caps;this.F="3"==this.o.A&&!!a.app.B&&!!a.app.B.g.textTracks;c=b=this.l=this.da=this.B=this.D=this.K=this.X=this.ka=
null;this.F||(b=new g.Kt(this.cD,void 0,this),g.N(this,b),c=new g.Nt(this.AS,2E3,this),g.N(this,c));this.ca=b;this.fa=c;this.W=new g.UE(this);g.N(this,this.W);this.F||this.W.O(a,"resize",this.Bu);this.W.O(a,"onPlaybackAudioChange",this.RN);this.W.O(a,"crn_captions",this.DK,this);this.W.O(a,"crx_captions",this.EK,this);T5(this,U5(this,"display-settings")||{})},Kwa=function(a){if(a.A.captionTracks.length)var b=a.g.wh().dw;
if("FORCED_ON"==b||1==a.o.Yg||1==a.A.Yg||"alwayson"==g.iN(a.A,"yt:cc"))return!0;if(2==a.o.Yg){var c=U5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.iN(a.A,"yt:cc")},Lwa=function(a,b){if(a.B){var c=C5(a.B.l,b||a.na);
if(a.D&&a.D.g)return a.D.g;for(var d=[a.A.Xg,a.o.Xg,g.iN(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(W4(c[f])==d[e])return c[f];return a.D&&a.D.Fq?a.D.Fq:c[0]||a.D&&a.D.Fk}return null},Mwa=function(a,b){for(var c=a.I.app.B.g.textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},W5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.N=c);a.l=b;a.load(d)},Nwa=function(a,b){var c=g.l0(a.ma,!0).height;
if(!c)return null;var d=a.ma.Sa();switch(null!=b.params.Bs?b.params.Bs:b.params.oT?2:1<b.l.length?1:0){case 1:return new L5(b,a.C,a.H,c,d.width,d.height);case 2:return new M5(b,a.C,a.H,c,d.width,d.height);default:return new b5(b,a.C,a.H,c,d.width,d.height)}},T5=function(a,b,c){var d=X5.kb;
a.C={};g.Ga(a.C,X5);a.C.kb={};g.Ga(a.C.kb,d);a.H={kb:{}};var e=b.backgroundOverride?a.H:a.C,f=b.background||d.background;s5.test(f);e.kb.background=f;e=b.colorOverride?a.H:a.C;f=b.color||d.color;s5.test(f);e.kb.color=f;e=b.windowColorOverride?a.H:a.C;f=b.windowColor||X5.windowColor;s5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ze);e.kb.Ze=f;e=b.fontSizeIncrementOverride?a.H:a.C;f=b.fontSizeIncrement;null==f&&(f=d.dj);e.kb.dj=f;e=b.textOpacityOverride?
a.H:a.C;f=b.textOpacity;null==f&&(f=d.Gh);e.kb.Gh=f;e=b.windowOpacityOverride?a.H:a.C;f=b.windowOpacity;null==f&&(f=X5.lk);e.lk=f;e=b.charEdgeStyleOverride?a.H:a.C;f=b.charEdgeStyle;null==f&&(f=d.Uh);e.kb.Uh=f;e=b.fontFamilyOverride?a.H:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.kb.fontFamily=f;a.loaded&&a.Bu();c&&Y5(a,"display-settings",b)},Pwa=function(a,b){if(b&&!a.K){var c=a5({ak:0,
lang:"en-GB"});a.K=[c,new Y4(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.UT(a.g,a.K)}else!b&&a.K&&(Owa(a,a.K),a.K=null)},Owa=function(a,b){g.WT(a.g,b);
(0,g.C)(b,function(a){g.Sa(this.M,a)},a);
a.ca.Nk()},Qwa=function(a,b){return a&&g.u(a)&&s5.test(a)?a:b},Rwa=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Twa=function(a,b){if(a&&g.u(a)){var c=Swa.indexOf(a);
return-1!=c?c:b}return b},Vwa=function(a,b){if(a&&g.u(a)){var c=Uwa.indexOf(a);
return-1!=c?c:b}return b},Wwa=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?g.Vc(a,-2,4):b},U5=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},Y5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.rH.prototype.Hn=g.da(4,function(a){return(a=this.Zh(a))?a.l:0});
g.AJ.prototype.Hn=g.da(3,function(){return 0});
g.lH.prototype.I=g.da(2,function(a){return a?this.toString()==a.toString():!1});
var Cwa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,awa=/#(.)(.)(.)/,$va=/^#(?:[0-9a-f]{3}){1,2}$/i,s5=/^#(?:[0-9a-f]{3}){1,2}$/i,Uwa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Swa=["none","raised","depressed","uniform","dropShadow"];var cwa=["left","right","center"];var X5={windowColor:"#080808",lk:0,textAlign:2,Ug:7,pi:50,Ni:100,kb:{background:"#080808",Ze:.75,Uh:0,color:"#fff",fontFamily:4,dj:0,Gh:1,offset:1}};g.p(Y4,g.UO);g.p(Z4,g.UO);var $4=0;g.p(b5,g.X);g.h=b5.prototype;g.h.ZK=function(a,b){var c=g.yh(this.element,this.element.parentElement);this.ba=a-c.x;this.ca=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.YK=function(a,b){var c=g.Bh(this.element),d=a-this.ba-.02*this.wa,e=b-this.ca-.02*this.na,f=(d+c.width/2)/this.W*3;f=Math.floor(g.Vc(f,0,2));var k=(e+c.height/2)/this.da*3;k=Math.floor(g.Vc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.W;d=100*g.Vc(d,0,1);c=(e+k/2*c.height)/this.da;c=100*g.Vc(c,0,1);this.D.params.Ug=l;this.D.params.Ni=c;this.D.params.pi=d;this.l.Ug=l;this.l.Ni=c;this.l.pi=d;this.YB()};
g.h.XK=function(){g.kq(this.element,"ytp-dragging")};
g.h.YB=function(){this.Ki(this.o)};
g.h.Sb=function(){return this.type};
g.h.Ki=function(a){var b=Math.min(this.tx(),this.W),c=this.rx();g.ih(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.eq(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.pi+2,e=this.l.Ug;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.Ni+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ih(this.element,a)};
g.h.eq=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.I||this.o.length>b)b=0,this.I=!1,this.o=[],this.C=[],this.F=[],this.B=null,g.Cd(this.A);for(;b<a.length;b++)dwa(this,a[b])};
g.h.tx=function(){return 0};
g.h.rx=function(){return 0};ewa.prototype.A=function(){};e5.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
e5.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var fwa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];f5.prototype.set=function(a){this.g=a};
f5.prototype.get=function(){return this.g};
g5.prototype.clear=function(){this.g=0};
g5.prototype.update=function(){this.g=2==this.g?1:0};
g5.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
h5.prototype.gn=function(a){this.te=a.te;this.timestamp=a.timestamp;this.g=a.g};
h5.prototype.reset=function(){this.timestamp=this.te=0;this.g=!1};
i5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.te?a+"_":a+String.fromCharCode(d.te)}a+="\n"}return a};
i5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.Ec=1};
var kwa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],lwa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],mwa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],nwa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];o5.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
d5.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};q5.prototype.reset=function(){};g.p(r5,q5);r5.prototype.g=function(a){var b=[];this.l||(this.l=a5(this.o),b.push(this.l));a=g.na(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())twa(c.value,this.l.id,b);return b};g.p(t5,q5);
t5.prototype.g=function(a){var b=[];this.l||(this.l=a5(),this.o[this.l.id]=this.l,b.push(this.l));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.o[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=a5());
var k={};f&&(g.Ga(k,f.params),f=f.params.kb)&&(k.kb={},g.Ga(k.kb,f));e.getAttribute("rc")&&(k.Uo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.NG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Ug=0>f||8<f?7:f);e.getAttribute("ah")&&(k.pi=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Ni=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.ak=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.ak=0));e.getAttribute("bc")&&(k.kb||(k.kb={}),k.kb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.kb||(k.kb={}),k.kb.Ze=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.kb||(k.kb={}),k.kb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.oT=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new Z4(c,f,0,e,k)}else c=null}this.o[d]=c;b.push(c);break;case "text":for(d=[],twa(a,this.l.id,d),d=g.na(d),c=d.next();!c.done;c=d.next())c=c.value,this.o[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(u5,q5);
u5.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.na(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())if(b=b.value,1==b.nodeType)switch(b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.na(c.childNodes),a=c.next();!a.done;a=c.next())if(a=a.value,1==a.nodeType)switch(a.tagName){case "pen":b=a.getAttribute("id");var e=this.l,f={},k=a.getAttribute("p");k&&g.Ga(f,this.l[k]);k=w5(a,"b");null!=k&&(f.bold=k);k=w5(a,"i");null!=k&&(f.ks=k);k=w5(a,"u");null!=
k&&(f.underline=k);k=x5(a,"et");null!=k&&(f.Uh=k);k=x5(a,"of");null!=k&&(f.offset=k);k=y5(a,"bc");null!=k&&(f.background=k);k=y5(a,"ec");null!=k&&(f.mw=k);k=y5(a,"fc");null!=k&&(f.color=k);k=x5(a,"fs");void 0!=k&&0!=k&&(f.fontFamily=k);k=v5(a,"sz");void 0!=k&&(f.dj=k/100-1);k=v5(a,"bo");void 0!=k&&(f.Ze=k/255);a=v5(a,"fo");void 0!=a&&(f.Gh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.C[b]=uwa(this,a);break;case "wp":b=a.getAttribute("id"),this.B[b]=vwa(this,a)}c=[];if(d)for(a={},b=void 0,
d=g.na(d.childNodes),e=d.next();!e.done;e=d.next())if(e=e.value,1==e.nodeType)switch(e.tagName){case "w":var l=wwa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=wd;f=[];k=e.getAttribute("w")||this.o;var q=!!w5(e,"a"),r=v5(e,"t")||0,v=v5(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?6:5;n=this.l[e.getAttribute("p")];for(var B=e.childNodes,G=0;G<B.length;G++){var L=B[G];0<G&&(q=!0);var Y=void 0;1==L.nodeType&&(Y=L);if(Y&&"s"==Y.tagName){var ka=
Y;L=r;Y=v;var $a=k,ba=q,dd=m,Cf=ka.textContent?ka.textContent:"",yb=this.l[ka.getAttribute("p")];ka=v5(ka,"t")||0;L=new Y4(L+ka,Y-ka,dd,$a,Cf,ba,yb)}else L=new Y4(r,v,m,k,L.textContent||"",q,n);f.push(L)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var wd=null!=e.getAttribute("d");f[0].windowId==this.o&&(l=wwa(this,e,!0),c.push(l));e=g.na(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.l.push(f),c.push(f)}}return c};g.p(z5,ewa);z5.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+$4++;c=c/1E3-this.D;d=d/1E3-this.D;a=new Z4(c,d-c,5,f,{textAlign:0,Ug:0,pi:2.5*b,Ni:5.33*a});e=new Y4(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(B5,q5);B5.prototype.g=function(a){a=new z5(a,a.byteLength,this.o);if(ywa(a)){for(;a.g<a.l.byteLength;)for(0==a.version&&(a.C=xwa(a)*(1E3/45)),a.B=A5(a);0<a.B;a.B--){var b=A5(a),c=A5(a),d=A5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.l,b.g.push({time:a.C,type:this.track,hw:c,iw:d,order:b.g.length}))}jwa(this.l,a);return a.o}return[]};
B5.prototype.reset=function(){this.l.clear()};g.p(E5,q5);
E5.prototype.g=function(a,b){for(var c=[],d=a.split(Xwa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Ywa.test(f)){var l=Z5.exec(f);if(l&&3<=l.length){var m=F5(l[1]);l=F5(l[2])-m;m+=k;f=f.substring(Z5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");Z5.lastIndex=0;var n=f;f={};this.l||(this.l=a5({Bs:0}),c.push(this.l));var q=this.l;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new Y4(m,l,k,q.id,n,!1,g.Tb(f)?void 0:f));else{n=n.split(Zwa);1!=n.length&&(k=6,q="_"+$wa++,q=new Z4(m,l,k,q,{}),c.push(q));
for(var r=m,v=0;v<n.length;v++){var B=n[v];if(0==v%2){var G=g.Nr("<html>"+B+"</html>");if(G.getElementsByTagName("parsererror").length){var L=G.createElement("span");L.appendChild(G.createTextNode(B))}else L=G.firstChild;Bwa(this,r,l-(r-m),k,q,0<v,L,f,c)}else r=F5(B)}}}Z5.lastIndex=0}}return c};
var $wa=0,Ywa=/^NOTE/,Xwa=/(?:\r\n|\r|\n){2,}/,Z5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Zwa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(G5,g.M);G5.prototype.trackCount=function(){return C5(this.l,!0).length};
G5.prototype.Id=function(){this.g=null};
G5.prototype.U=function(){g.M.prototype.U.call(this);this.Id()};
G5.prototype.KB=function(){return!1};g.p(H5,G5);g.h=H5.prototype;g.h.us=function(a,b){var c=this.Lk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Id();this.o=g.DD(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.ws=function(a,b,c,d){this.A=c;if(d)for(b=g.na(d.captionTracks),c=b.next();!c.done;c=b.next())D5(this.l,c.value);a()};
g.h.Lk=function(a){var b=a.Oa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.wD(b,c)};
g.h.Id=function(){G5.prototype.Id.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Id();G5.prototype.U.call(this)};I5.prototype.contains=function(a){a=g.cb(this.qb,a);return 0<=a||0>a&&1==(-a-1)%2};
I5.prototype.length=function(){return this.qb.length/2};g.p(J5,g.M);g.h=J5.prototype;g.h.U=function(){g.M.prototype.U.call(this);this.l&&this.l.abort()};
g.h.wz=function(a){var b=this.g;this.g=g.Ia(this.K.hh(a).xa);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.A=new I5;this.l&&(this.l.abort(),this.l=null)};
g.h.Ky=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.wi(a);!a||this.l||this.g&&30<this.g.startTime-this.C.getCurrentTime()||(a=this.g,a=a.g.jl(a),!g.W(this.C).experiments.g("disable_captions_unknown_requests")&&!a.xa[0].duration)||(this.A.contains(a.xa[0].ra)||Fwa(this,a),this.g=g.Ia(a.xa));this.F.start()};
g.h.MQ=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status;if(!g.W(this.C).experiments.g("disable_captions_redirects_redux")){var c=g.FJ(a);if(c){a=g.lJ(this.o,{});b=this.o;g.jJ(b.g,a,c);b.requestId=a.get("req_id");Fwa(this,this.o);return}}b||null===this.D||(this.B?this.D(a.response,1E3*this.o.xa[0].startTime):this.D(a.responseText,1E3*this.o.xa[0].startTime));this.l=this.o=null};g.p(K5,G5);g.h=K5.prototype;g.h.us=function(a,b){this.Id();var c=Gwa(this,a.l);if(c){var d=1E3*c.index.Hn(c.index.wg()),e=g.W(this.B).Wa;this.o=new J5(new g.TI,this.B,c,function(c,e){b(c,a,e,d)},e||g.tG(c.info),(0,g.z)(function(){e&&(this.o&&this.o.reset(),this.g&&this.g.reset(),this.C=!0)},this))}};
g.h.KB=function(){var a=this.C;this.C=!1;return a};
g.h.ws=function(a){g.W(this.B).Wa?(D5(this.l,new g.lH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),D5(this.l,new g.lH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):D5(this.l,new g.lH({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Id=function(){G5.prototype.Id.call(this);this.o&&(this.o.dispose(),this.o=null)};
g.h.Lk=function(){return""};
g.h.U=function(){this.Id();G5.prototype.U.call(this)};g.p(L5,b5);L5.prototype.eq=function(a){var b=this.D.l;b5.prototype.eq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ga(d,c.l);g.Ga(d,axa);var e=c.l;var f=d}dwa(this,c,d)}};
var axa={wr:!0};g.p(M5,b5);g.h=M5.prototype;g.h.YB=function(){g.Pt(this.X)};
g.h.QQ=function(){g.kq(this.element,"ytp-rollup-mode");this.Ki(this.ka,!0)};
g.h.tx=function(){return this.H};
g.h.rx=function(){return this.D.params.Uo*N5(this)};
g.h.Ki=function(a,b){this.ka=a;if(N5(this)){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));c=this.H;this.H=0;b5.prototype.Ki.call(this,a);this.H=Math.max(c,this.A.offsetWidth+1);c=this.D.params.Uo*N5(this)-this.A.offsetHeight;c!=this.N&&(b||(0,window.isNaN)(this.N)||(g.S(this.element,"ytp-rollup-mode"),g.Ot(this.X)),g.ih(this.A,"transform",c?"translateY("+c+"px)":""),this.N=c);b5.prototype.Ki.call(this,a)}else b5.prototype.Ki.call(this,
a)};g.p(O5,G5);g.h=O5.prototype;g.h.us=function(a,b){var c=this.Lk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Id();this.o=g.DD(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.ws=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.vy&&(b.asrs=1);d=g.wD(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.na(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),B=m.getAttribute("id"),G="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");D5(d,new g.lH({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:v,id:B,is_servable:!0,is_translateable:G,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.C[l.languageCode]=l.languageName,this.D.push(new g.kH(l))}a()},this);
this.Id();this.o=g.DD(d,{format:"RAW",Hb:b,withCredentials:!0})};
g.h.Lk=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:a.o};a.g&&(c.tlang=W4(a));return b=g.wD(b,c)};
g.h.Id=function(){G5.prototype.Id.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Id();G5.prototype.U.call(this)};g.p(P5,g.u_);g.h=P5.prototype;g.h.qf=function(a){g.u_.prototype.qf.call(this,a)};
g.h.hA=function(a){return a.option.toString()};
g.h.pf=function(a){return Iwa(this.K[a])};
g.h.md=function(a){g.u_.prototype.md.call(this,a);this.P("settingChange",this.I,this.K[a].option)};
g.h.iA=function(a){this.P("settingChange",this.I+"Override",!a);this.A.Ue()};g.p(Q5,g.fZ);Q5.prototype.o=function(a,b){this.P("settingChange",a,b)};g.p(R5,g.u_);R5.prototype.B=function(a){return a.languageCode};
R5.prototype.pf=function(a){return this.l[a].languageName||""};
R5.prototype.md=function(a){this.P("select",a);g.oZ(this.A)};g.p(S5,g.u_);g.h=S5.prototype;g.h.zt=function(a){return g.Tb(a)?"__off__":a.displayName};
g.h.pf=function(a){return"__off__"==a?g.U("YTP_LANGUAGE_OFF"):"__translate__"==a?g.U("YTP_AUTO_TRANSLATE"):"__contribute__"==a?g.U("YTP_CONTRIBUTE_MENU_ITEM"):("__off__"==a?{}:this.B[a]).displayName};
g.h.md=function(a){"__translate__"==a?this.F.open():"__contribute__"==a?(this.l.ld(),this.l.isFullscreen()&&g.KT(this.l),a=g.hO(g.W(this.l),this.l.ea()),g.sU(a)):(this.l.Hd("captions","track","__off__"==a?{}:this.B[a]),g.u_.prototype.md.call(this,a),this.A.Ue())};
g.h.yl=function(){var a=-1!=this.l.xi().indexOf("captions"),b=this.l.ea().vk;if(a||b){if(a){var c=this.l.wc("captions","track");var d=this.l.wc("captions","tracklist",{includeAsr:!0});var e=this.l.wc("captions","translationLanguages");this.B=g.ib(d,this.zt,this);var f=(0,g.I)(d,this.zt);if(e.length){var k=this.F;var l=e;k.l=g.ib(l,k.B,k);g.v_(k,(0,g.I)(l,k.B));f.push("__translate__")}k=this.zt(c)}else this.B={},f=[],k="__off__";f.unshift("__off__");this.B.__off__={};b&&f.unshift("__contribute__");
this.B[k]||(this.B[k]=c,f.push(k));g.v_(this,f);this.qf(k);a?(Jwa(this.K,this.l.yi()),this.I.Yb(d.length?" ("+d.length+")":""),this.P("size-change"),a&&e.length&&this.o.__translate__.element.setAttribute("aria-disabled",!!g.Tb(c))):(this.I.Yb(""),this.P("size-change"));this.enable(!0)}else this.enable(!1)};
g.h.gA=function(a){this.l.Hd("captions","sampleSubtitles",a)};
g.h.eN=function(a){var b=this.l.wc("captions","track");b=g.Xb(b);b.translationLanguage=this.F.l[a];this.l.Hd("captions","track",b)};
g.h.dN=function(a,b){if("reset"==a)this.l.Zs();else{var c={};c[a]=b;this.l.wo(c)}this.gA(!0);this.M.start();Jwa(this.K,this.l.yi())};
g.h.U=function(){g.Qt(this.M);g.u_.prototype.U.call(this)};g.p(V5,g.hU);g.h=V5.prototype;g.h.U=function(){if(this.F){var a=this.I.app.B;a&&Yva(a)}else Pwa(this,!1);g.hU.prototype.U.call(this)};
g.h.mz=function(){return this.F?!this.A.ya:this.A.captionTracks.length&&this.g.wh().Fk?!0:Kwa(this)};
g.h.load=function(a){g.hU.prototype.load.call(this);this.D=this.g.wh();var b=this.I.C;b&&(this.da=new S5(this.I,b));if(this.B||a)this.l?(this.F&&!this.o.experiments.g("disable_native_caption_api")?Mwa(this,!0):a?this.tB(a,this.l):3!=this.g.Qa()&&this.B.us(this.l,(0,g.z)(this.tB,this)),this.g.pa("captionschanged",V4(this.l))):this.g.pa("onCaptionsTrackListChanged");else{var c;Hwa(this.A,this.I)?c=new K5(this.A.oa,this.g):this.A.captionTracks.length?c=new H5(this.A):c=new O5(this.A.Um,this.A.videoId,
this.A.Xg||this.o.Xg||g.iN(this.A,"yt:cc_default_lang")||this.o.Pa,this.A.Tm);this.B=c;c.ws((0,g.z)(this.rR,this),!0,this.F?"vtt":void 0,this.g.wh())}};
g.h.unload=function(){this.F?this.o.experiments.g("disable_native_caption_api")?Yva(this.I.app.B):this.l&&Mwa(this,!1):(this.fa&&g.Qt(this.fa),g.XT(this.g,"captions"),this.M=[],this.B&&this.B.Id(),this.K&&g.UT(this.g,this.K),this.Bu());this.da&&(this.da.dispose(),this.da=null);g.hU.prototype.unload.call(this);var a=g.FT(this.g.app);a&&a.C&&g.lO(a.C.o);this.g.pa("captionschanged",{})};
g.h.rR=function(){if(this.N||Kwa(this))var a=Lwa(this,this.N);if(this.F){for(var b=C5(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.mH(e),srclang:W4(e),src:this.B.Lk(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}a=this.I.app.B;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.I.app.B.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.o.experiments.g("disable_native_caption_api")&&this.W.O(c.textTracks,"change",this.sR)}else!this.l&&a&&W5(this,
a),this.g.pa("onCaptionsTrackListChanged"),this.g.pa("onApiChange")};
g.h.sR=function(){for(var a=this.I.app.B.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=C5(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&W5(this,b,!0)};
g.h.zT=function(){this.o.experiments.g("disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.l&&this.F||this.unload()};
g.h.tB=function(a,b,c,d){if(a){this.B.KB()&&(this.M=[],g.XT(this.I,"captions"),this.ca.Nk());a=Ewa(this.B,a,b,c,d);g.UT(this.g,a);if(this.N&&(a={trackName:b.B,trackKind:b.A,trackLangCode:W4(b)},b.g&&(a.fromLangCode=b.l),g.OT(this.g,"cc",a),this.l!=(this.D&&this.D.Fk))){!this.N||g.kL(this.o)||g.AL(this.o)||(g.Qt(this.fa),b=a5({Ug:0,pi:5,Ni:5,Uo:2,textAlign:0,ak:0,lang:"en-GB"}),this.X=[b],a=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.ka||(c=new g.kU(g.VU()),g.N(this,c),this.ka=c.element),
c=b.end-b.start,(d=g.mH(this.l))&&this.X.push(new Y4(b.start,c,0,b.id,d)),this.X.push(new Y4(b.start,c,0,b.id,a[0]),new Y4(b.start,c,0,b.id,this.ka,!0),new Y4(b.start,c,0,b.id,a[1],!0)),g.UT(this.g,this.X),g.Ot(this.fa));if(this.N||g.kL(this.o))Y5(this,"module-enabled",!0),this.D&&(this.D.g=this.l);(b=g.FT(this.g.app))&&b.C&&g.lO(b.C.o)}this.N=!1}};
g.h.DK=function(a){this.M.push(a);this.ca.Nk()};
g.h.EK=function(a){g.Sa(this.M,a);var b=Hwa(this.A,this.I)&&this.o.Wa;!this.o.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.WT(this.g,[a]);this.ca.Nk()};
g.h.mS=function(a){if(a instanceof Z4){var b=this.V[a.id];b&&b.D!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=Nwa(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.AS=function(){Owa(this,this.X);this.X=null};
g.h.cD=function(){this.ca.stop();g.Ub(this.Y);this.M.sort(g.WO);var a=this.M;if(this.K){var b=(0,g.Gd)(a,function(a){return-1==this.K.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.mS,this);g.Hb(this.V,function(a,b){this.Y[b]?(a.element.parentNode||g.bU(this.g,a.element,4),a.Ki(this.Y[b])):(a.dispose(),delete this.V[b])},this)};
g.h.XB=function(){T5(this,{},!0)};
g.h.Wq=function(){var a=X5.kb;a={background:a.background,backgroundOpacity:a.Ze,charEdgeStyle:a.Uh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.dj,textOpacity:a.Gh,windowColor:X5.windowColor,windowOpacity:X5.lk};var b=U5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Eu=function(a,b){var c={};g.Ga(c,U5(this,"display-settings"));g.Ga(c,a);T5(this,c,b);this.g.P("captionssettingschanged")};
g.h.Bu=function(){!this.F&&this.loaded&&(g.Hb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.cD())};
g.h.Ks=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Vc(b,-2,4);this.Eu({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&W5(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.o.Gb&&Y5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Ca(b))break;if(g.Tb(b)){W5(this,null,!0);break}for(var d=C5(this.B.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.C!=b.languageName||(c=b.translationLanguage?Xva(f,
b.translationLanguage):f)}!c||c==this.l&&this.loaded||W5(this,c,!0)}else return this.loaded&&this.l&&this.l!=(this.D&&this.D.Fk)?V4(this.l):{};return"";case "tracklist":return this.B?(0,g.I)(C5(this.B.l,!(!b||!b.includeAsr)),function(a){return V4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":c=this.Wq();if(g.kL(this.o)&&b&&g.Ca(b))if(b.reset)this.XB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Qwa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Rwa(b[d],c[d]);break;case "charEdgeStyle":f[d]=Twa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=Wwa(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=Vwa(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Eu(f,!0);c=this.Wq()}c.fontFamilyOption=Uwa[c.fontFamily];c.charEdgeStyle=Swa[c.charEdgeStyle];return c;case "sampleSubtitles":this.F||void 0==b||Pwa(this,!!b);break;case "xmlTrack":b&&this.o.Gb&&(this.F||W5(this,new g.lH({languageName:b.name}),!1,b.xml))}};
g.h.BK=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.o.Gb&&a.push("stickyLoading","xmlTrack");return a};
g.h.CK=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.NC=function(){this.loaded&&this.l?(Y5(this,"module-enabled",!1),this.unload()):W5(this,this.l||Lwa(this,!0),!0)};
g.h.RN=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),this.mz()&&this.load())};g.a0.captions=V5;})(_yt_player);
