(function(g){var window=this;var bxa=function(a,b,c,d){var e=b.dc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.jd(c,d?d:"mqdefault.jpg");var k=b instanceof g.UM?g.cV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.XO(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.UM?b.ya:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Ln(c),is_live:m,is_list:l,
is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.ZO&&(c.playlist_length=b.getLength());a.update(c)},$5=function(a,b){g.CU.call(this,{G:"div",
aa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},a6=function(a){var b={G:"span",
L:"ytp-upnext-top",J:[{G:"span",L:"ytp-upnext-header",J:[g.U("YTP_PLAYLIST_UP_NEXT")]},{G:"span",L:"ytp-upnext-title",J:["{{title}}"]},{G:"span",L:"ytp-upnext-author",J:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={G:"div",L:"ytp-upnext",T:{"aria-label":"{{watch}}"},J:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},b,{G:"a",L:"ytp-upnext-autoplay-icon",T:c,J:[{G:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},
J:[{G:"circle",L:"ytp-svg-autoplay-circle",T:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{G:"circle",L:"ytp-svg-autoplay-ring",T:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{G:"polygon",L:"ytp-svg-autoplay-triangle",T:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{G:"span",L:"ytp-upnext-bottom",J:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",J:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]}]};
g.X.call(this,b);this.A=null;b=this.sa["ytp-upnext-cancel"];this.A=new g.X({G:"button",aa:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":g.U("YTP_AUTOPLAY_CANCEL")},J:[g.U("YTP_CANCEL")]});g.N(this,this.A);this.A.R("click",this.ZN,this);this.A.Ba(b);this.l=a;this.I=this.sa["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.F=new g.Nt(this.an,5E3,this);g.N(this,this.F);this.H=0;this.O(this.sa["ytp-upnext-autoplay-icon"],"click",this.iQ);this.GA();this.O(a,"autonavvisibility",
this.GA);this.O(a,"mdxnowautoplaying",this.xP);this.O(a,"mdxautoplaycanceled",this.yP);this.O(a,"mdxautoplayupnext",this.gD);3==this.l.Qa()&&(a=(a=g.ET(g.zT(this.l)))?a.rH():null)&&this.gD(a)},cxa=function(a,b){a.B=b;
bxa(a,b,g.W(a.l),"hqdefault.jpg")},b6=function(a,b){if(!a.o){g.kF("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title);
a.H=g.wF();a.o=new g.Nt((0,g.z)(a.bq,a,b),25);a.bq(b);var c=b||g.W(a.l).experiments.l("autoplay_time")||1E4;a.l.pa("onAutonavCoundownStarted",c)}g.kq(a.element,"ytp-upnext-autoplay-paused")},d6=function(a){c6(a);
a.H=g.wF();a.bq();g.S(a.element,"ytp-upnext-autoplay-paused")},c6=function(a){a.o&&(a.o.dispose(),a.o=null)},e6=function(a,b){b=void 0===b?!1:b;
var c=g.W(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.OT(a.l,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.dc(),a.an(),a.C=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.jd(c)}),a.D=a.O(a.C,"click",a.YP),a.F.start())}c6(a);a.l.Ej(!1,b)},dxa=function(a){$5.call(this,a,"subscribecard-endscreen");
var b=a.ea();this.o=new g.X({G:"div",L:"ytp-subscribe-card",J:[{G:"img",L:"ytp-author-image",T:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",J:[{G:"div",L:"ytp-author-name",J:[b.author]},{G:"div",L:"html5-subscribe-button-container"}]}]});g.N(this,this.o);this.o.Ba(this.element);this.A=new g.Q_(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Ol,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.A);this.A.Ba(this.o.sa["html5-subscribe-button-container"]);this.hide()},
f6=function(a){var b=g.W(a),c=g.RI||g.Xe?{style:"will-change: opacity"}:void 0,d=b.o&&!b.F,e=["ytp-videowall-still"];
b.experiments.g("web_player_video_wall_show_text")&&b.l&&e.push("ytp-videowall-show-text");g.X.call(this,{G:"a",aa:e,T:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",L:"ytp-videowall-still-image",T:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",J:[{G:"span",L:"ytp-videowall-still-info-bg",J:[{G:"span",L:"ytp-videowall-still-info-content",T:c,J:[{G:"span",L:"ytp-videowall-still-info-title",
J:["{{title}}"]},{G:"span",L:"ytp-videowall-still-info-author",J:["{{author_and_views}}"]},{G:"span",L:"ytp-videowall-still-info-live",J:[g.U("YTP_LIVE")]},{G:"span",L:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",aa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",
aa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{G:"span",L:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.A=d;this.l=a;this.o=null;this.R("click",this.B);this.R("keypress",this.C);g.W(a).Y&&(a=a.app.ca,b=this.element,g.D(a.g,b),g.Qa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.Se(this,(0,g.z)(a.D,a,b)))},g6=function(a){$5.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.A=[];this.H=this.D=this.C=null;this.I=this.X=!1;this.B=new g.UE(this);g.N(this,this.B);this.M=new g.Nt(g.Fa(g.S,this.element,"ytp-show-tiles"),0);g.N(this,this.M);var b=new g.X({G:"button",aa:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":g.U("YTP_PREVIOUS")},J:[g.GU()]});g.N(this,b);b.Ba(this.element);b.R("click",this.QK,this);this.N=new g.kU({G:"div",L:"ytp-endscreen-content"});g.N(this,this.N);this.N.Ba(this.element);b=new g.X({G:"button",aa:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":g.U("YTP_NEXT")},J:[g.HU()]});g.N(this,b);b.Ba(this.element);b.R("click",this.PK,this);this.o=new a6(a);g.N(this,this.o);g.bU(this.l,this.o.element,4);this.hide()},h6=function(a){return g.cU(a.l)&&a.gq()&&!a.H},exa=function(a){return(0,g.I)(a.suggestions,function(a){return g.IZ(a)})},i6=function(a){var b=a.Ns();
b!=a.X&&(a.X=b,a.l.P("autonavvisibility"))},j6=function(a){g.hU.call(this,a);
g.gG({YTP_AUTOPLAY_CANCEL:"Cancel autoplay",YTP_AUTOPLAY_NEXT:"Play next video",YTP_AUTOPLAY_PAUSED_3:"Auto-play is paused",YTP_CANCEL:"Cancel",YTP_MIX:"Mix",YTP_PLAYLIST_UP_NEXT:"Up Next",YTP_UNSUBSCRIBE:"Unsubscribe"});this.l=null;this.o=new g.UE(this);g.N(this,this.o);this.A=g.W(a);fxa(a)?this.l=new g6(this.g):this.A.fa?this.l=new dxa(this.g):this.l=new $5(this.g);g.N(this,this.l);g.bU(this.g,this.l.element,4);this.WB();this.o.O(a,"videodatachange",this.WB,this);this.o.O(a,"crn_endscreen",this.oK,
this);this.o.O(a,"crx_endscreen",this.pK,this)},fxa=function(a){a=g.W(a);
return a.Ld&&!a.fa};
g.p($5,g.CU);$5.prototype.create=function(){this.created=!0};
$5.prototype.destroy=function(){this.created=!1};
$5.prototype.gq=function(){return!1};
$5.prototype.Ns=function(){return!1};g.p(a6,g.X);g.h=a6.prototype;g.h.an=function(){this.C&&(this.F.stop(),this.Ca(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.GA=function(){g.tU(this,g.AT(this.l))};
g.h.YP=function(){window.focus();this.an()};
g.h.hide=function(){g.X.prototype.hide.call(this)};
g.h.bq=function(a){a=a||g.W(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.wF()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.l.Qa()?e6(this,!0):this.o&&this.o.start()};
g.h.iQ=function(a){!g.Ld(this.A.element,g.JE(a))&&g.eX(a,this.l)&&e6(this)};
g.h.ZN=function(){g.CT(this.l,!0)};
g.h.xP=function(a){this.l.Qa();this.show();b6(this,a)};
g.h.gD=function(a){this.l.Qa();this.B&&this.B.dc().videoId==a.dc().videoId||cxa(this,a)};
g.h.yP=function(){this.l.Qa();c6(this);this.hide()};
g.h.U=function(){c6(this);this.an();g.X.prototype.U.call(this)};g.p(dxa,$5);g.p(f6,g.X);f6.prototype.Tj=function(){g.fU(this.l,this.element);var a=this.o.dc().videoId,b=this.o.getPlaylistId();g.S0(this.l.app,a,this.o.Yd,b,void 0,void 0,void 0)};
f6.prototype.B=function(a){g.eX(a,this.l,this.A,this.o.Yd||void 0)&&this.Tj()};
f6.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.OE(a)||(this.Tj(),g.NE(a))}};g.p(g6,$5);g.h=g6.prototype;g.h.create=function(){$5.prototype.create.call(this);var a=this.l.ea();a&&(this.C=exa(a),this.D=a);this.Fg();this.B.O(this.l,"appresize",this.Fg);this.B.O(this.l,"onVideoAreaChange",this.Fg);this.B.O(this.l,"videodatachange",this.RK);this.B.O(this.l,"autonavchange",this.pz);this.B.O(this.l,"autonavcancel",this.OK);this.B.O(this.element,"transitionend",this.tR)};
g.h.destroy=function(){g.WE(this.B);g.Ue(this.A);this.A=[];this.C=null;$5.prototype.destroy.call(this);g.kq(this.element,"ytp-show-tiles");this.M.stop()};
g.h.gq=function(){return 1!=this.D.autonavState};
g.h.show=function(){$5.prototype.show.call(this);g.kq(this.element,"ytp-show-tiles");g.W(this.l).l?g.Pt(this.M):this.M.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.CT(this.l,!1);var a=h6(this);g.cU(this.l)&&g.W(this.l).experiments.g("ui_logging")&&g.OT(this.l,"end",{cancelButtonShow:a?"1":"0",state:this.gq()?"enabled":"disabled"});a?(i6(this),2==this.D.autonavState?g.W(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.zi()?e6(this.o,!0):b6(this.o):3==this.D.autonavState&&
d6(this.o)):(g.CT(this.l,!0),i6(this))};
g.h.hide=function(){$5.prototype.hide.call(this);d6(this.o);i6(this)};
g.h.tR=function(a){g.JE(a)==this.element&&this.Fg()};
g.h.Fg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");if(g.W(this.K).experiments.g("web_player_endscreen_size_killswitch"))var a=g.Bh(this.element);else{a=g.RT(this.K);var b=g.zT(this.K).H;b&&(b=b.Td()?48:32,a.width-=2*b)}var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,v=b<=f-2&&n>=r*m,B=e<=k-2&&n>=q*m;if((q+
1)/r*d/c>c/(q/(r+1)*d)&&B)n-=q*m,e+=2;else if(v)n-=r*m,b+=2;else if(B)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Vc(a.width/m||1,1,1.21);n*=g.Vc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Ah(a,m,n);g.ih(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});cxa(this.o,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",h6(this));i6(this);m+=4;
n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.Wc(q+this.F,l),0!=r){v=this.A[c];v||(v=new f6(this.l),this.A[c]=v,a.appendChild(v.element));B=Math.floor(n*k/e);var G=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-B-4,Y=Math.floor(m*(f+r)/b)-G-4;g.ph(v.element,G,B);g.Ah(v.element,Y,L);g.ih(v.element,"transitionDelay",(k+f)/20+"s");g.T(v.element,"ytp-videowall-still-mini",1==r);g.T(v.element,"ytp-videowall-still-large",2<r);r=v;
q=this.C[q];r.o=q;bxa(r,q,g.W(r.l),g.iq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");v=q.Yd;q=r.l;g.W(q).Y&&(q=q.app.ca,r=r.element,v=v&&v.itct,B=r.getAttribute("data-visual-id"),g.D(q.g,r),g.dU(q,"onLogServerVeCreated",{id:B,tracking_params:v}));c++}g.T(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Ed(e.element),g.Te(e);this.A.length=c}};
g.h.RK=function(){var a=this.l.ea();this.D!=a&&(this.F=0,this.C=exa(a),this.D=a,this.Fg())};
g.h.PK=function(){this.F+=this.A.length;this.Fg()};
g.h.QK=function(){this.F-=this.A.length;this.Fg()};
g.h.uJ=function(){return!!this.o.o};
g.h.pz=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,c6(this.o),this.g&&this.Fg()):(this.I=!0,this.g&&h6(this)&&(2==a?b6(this.o):3==a&&d6(this.o)))};
g.h.OK=function(a){if(a){for(a=0;a<this.A.length;a++)g.gU(this.K,this.A[a].element,!0);this.pz(1)}else this.H=null,this.I=!1;this.Fg()};
g.h.Ns=function(){return this.g&&h6(this)};g.p(j6,g.hU);g.h=j6.prototype;g.h.lz=function(){var a=this.g.ea(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!fxa(this.g)||b;a=g.mN(a,"ypc_module");var c=g.T0(this.g.app);return b&&!a&&!c};
g.h.kz=function(){return this.l.Ns()};
g.h.qJ=function(){return this.kz()?this.l.uJ():!1};
g.h.U=function(){g.XT(this.g,"endscreen");g.hU.prototype.U.call(this)};
g.h.load=function(){g.hU.prototype.load.call(this);this.l.show();g.W(this.g).fa&&.01>Math.random()&&g.OT(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.hU.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.oK=function(a){this.lz()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.pK=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.WB=function(){g.XT(this.g,"endscreen");var a=Math.max(1E3*(this.g.ea().lengthSeconds-10),0);a=new g.UO(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.UO(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.UT(this.g,[a,b])};g.a0.endscreen=j6;})(_yt_player);
